
import { Facility } from './types';

export const MOCK_FACILITIES: Facility[] = [
  {
    id: 'p1',
    name: 'Cubbon Park Public Restroom',
    type: 'Park',
    address: 'Kasturba Road, Sampangi Rama Nagar, Bengaluru',
    shortAddress: 'Kasturba Rd, near High Court',
    addressLine1: 'Kasturba Road, near High Court Entrance',
    addressLine2: 'Sampangi Rama Nagar, Bengaluru',
    distance: 0.4,
    rating: 3.9,
    cleanlinessRating: 3.5,
    isOpen: true,
    isFree: true,
    hasWheelchairAccess: true,
    hasStrollerAccess: true,
    hasDiaperChange: false,
    hasFeedingArea: false,
    imageUrl: 'https://images.unsplash.com/photo-1585938389612-a552a28d6914?auto=format&fit=crop&q=80&w=400',
    location: { lat: 12.9733, lng: 77.5921 },
    locationDetails: 'Near High Court Entrance',
    toiletStyle: 'Indian and Western',
    isRoadside: true,
    diversionDistance: 0.1,
    openTime: '06:00 AM',
    closeTime: '08:00 PM',
  },
  {
    id: 'p2',
    name: 'Lalbagh West Gate Utility',
    type: 'Park',
    address: 'Mavalli, Bengaluru',
    shortAddress: 'Lalbagh West Gate, Mavalli',
    addressLine1: 'Near West Gate Entrance, Lalbagh',
    addressLine2: 'Mavalli, South Bengaluru',
    distance: 1.2,
    rating: 4.1,
    cleanlinessRating: 4.0,
    isOpen: true,
    isFree: false,
    hasWheelchairAccess: true,
    hasStrollerAccess: true,
    hasDiaperChange: true,
    hasFeedingArea: false,
    imageUrl: 'https://images.unsplash.com/photo-1596438611181-a02e6047702a?auto=format&fit=crop&q=80&w=400',
    location: { lat: 12.9507, lng: 77.5844 },
    locationDetails: 'Next to Glass House',
    toiletStyle: 'Western',
    isRoadside: false,
    diversionDistance: 0.5,
    openTime: '06:00 AM',
    closeTime: '07:00 PM',
  },
  {
    id: 'p3',
    name: 'JP Park Smart Restroom',
    type: 'Park',
    address: 'Brindavan Nagar, Mathikere, Bengaluru',
    shortAddress: 'Mathikere, near Play Area',
    addressLine1: 'Brindavan Nagar, near Play Area',
    addressLine2: 'Mathikere, North Bengaluru',
    distance: 4.5,
    rating: 4.3,
    cleanlinessRating: 4.4,
    isOpen: true,
    isFree: false,
    hasWheelchairAccess: true,
    hasStrollerAccess: true,
    hasDiaperChange: true,
    hasFeedingArea: true,
    imageUrl: 'https://images.unsplash.com/photo-1588880331179-bc9b93a8cb5e?auto=format&fit=crop&q=80&w=400',
    location: { lat: 13.0333, lng: 77.5583 },
    locationDetails: 'Near Children\'s Play Area',
    toiletStyle: 'Western',
    isRoadside: false,
    openTime: '05:30 AM',
    closeTime: '09:00 PM',
  },
  {
    id: 's1',
    name: 'Swachh Smart Toilet - Brigade Road',
    type: 'Public Pay & Use',
    address: 'Brigade Road, Shantala Nagar, Ashok Nagar',
    shortAddress: 'Brigade Rd, near MG Road Jnc',
    addressLine1: 'Brigade Road, Near MG Road Junction',
    addressLine2: 'Shantala Nagar, Ashok Nagar',
    distance: 0.2,
    rating: 4.4,
    cleanlinessRating: 4.5,
    isOpen: true,
    isFree: false,
    hasWheelchairAccess: true,
    hasStrollerAccess: true,
    hasDiaperChange: false,
    hasFeedingArea: false,
    imageUrl: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&q=80&w=400',
    location: { lat: 12.9710, lng: 77.6067 },
    locationDetails: 'Near MG Road Junction',
    toiletStyle: 'Western',
    isRoadside: true,
    diversionDistance: 0,
    openTime: '05:00 AM',
    closeTime: '11:00 PM',
  },
  {
    id: 's2',
    name: 'e-Toilet Public Utility',
    type: 'Public Pay & Use',
    address: 'Indiranagar 100 Feet Rd',
    shortAddress: 'Indiranagar 100ft Rd, Pillar 120',
    addressLine1: '100 Feet Road, Near Metro Pillar 120',
    addressLine2: 'Indiranagar, East Bengaluru',
    distance: 1.5,
    rating: 4.0,
    cleanlinessRating: 4.2,
    isOpen: true,
    isFree: false,
    hasWheelchairAccess: true,
    hasStrollerAccess: false,
    hasDiaperChange: false,
    hasFeedingArea: false,
    imageUrl: 'https://images.unsplash.com/photo-1564540574859-0dfb63985953?auto=format&fit=crop&q=80&w=400',
    location: { lat: 12.9629, lng: 77.6442 },
    locationDetails: 'Near Metro Pillar 120',
    toiletStyle: 'Western',
    isRoadside: true,
    diversionDistance: 0.1,
    openTime: '06:00 AM',
    closeTime: '10:00 PM',
  },
  {
    id: '1',
    name: 'Phoenix Marketcity Toilet',
    type: 'Mall',
    address: 'Whitefield Main Rd, Devasandra Industrial Estate',
    shortAddress: 'Whitefield Main Rd, East Wing',
    addressLine1: 'Whitefield Main Rd, Level 2 East Wing',
    addressLine2: 'Devasandra Industrial Estate, Bengaluru',
    distance: 0.8,
    rating: 4.5,
    cleanlinessRating: 4.8,
    isOpen: true,
    isFree: true,
    hasWheelchairAccess: true,
    hasStrollerAccess: true,
    hasDiaperChange: true,
    hasFeedingArea: true,
    imageUrl: 'https://images.unsplash.com/photo-1595428774223-ef52624120d2?auto=format&fit=crop&q=80&w=400',
    location: { lat: 12.9958, lng: 77.6963 },
    floor: 'Level 2',
    locationDetails: 'East Wing, near Food Court',
    toiletStyle: 'Indian and Western',
    isRoadside: false,
    diversionDistance: 0.4,
    openTime: '10:00 AM',
    closeTime: '10:00 PM',
  }
];
