
import { Facility } from './types';

export const MOCK_FACILITIES: Facility[] = [
  {
    id: '12',
    name: 'Cubbon Park Public Toilet',
    type: 'Park',
    address: 'Kasturba Road, Sampangi Rama Nagar',
    distance: 0.4,
    rating: 3.9,
    cleanlinessRating: 3.5,
    isOpen: true,
    isFree: true,
    hasWheelchairAccess: true,
    hasStrollerAccess: true,
    hasDiaperChange: false,
    hasFeedingArea: false,
    imageUrl: 'https://images.unsplash.com/photo-1585938389612-a552a28d6914?auto=format&fit=crop&q=80&w=400',
    location: { lat: 12.9733, lng: 77.5921 },
    locationDetails: 'Near High Court Entrance',
    toiletStyle: 'Indian and Western',
    isRoadside: true,
    diversionDistance: 0.1,
    openTime: '06:00 AM',
    closeTime: '08:00 PM',
  },
  {
    id: '13',
    name: 'Lalbagh West Gate Utility',
    type: 'Park',
    address: 'Mavalli, Bengaluru',
    distance: 1.2,
    rating: 4.1,
    cleanlinessRating: 4.0,
    isOpen: true,
    isFree: false,
    hasWheelchairAccess: true,
    hasStrollerAccess: true,
    hasDiaperChange: true,
    hasFeedingArea: false,
    imageUrl: 'https://images.unsplash.com/photo-1596438611181-a02e6047702a?auto=format&fit=crop&q=80&w=400',
    location: { lat: 12.9507, lng: 77.5844 },
    locationDetails: 'Next to Glass House',
    toiletStyle: 'Western',
    isRoadside: false,
    diversionDistance: 0.5,
    openTime: '06:00 AM',
    closeTime: '07:00 PM',
  },
  {
    id: '1',
    name: 'Phoenix Marketcity Toilet',
    type: 'Mall',
    address: 'Whitefield Main Rd, Devasandra Industrial Estate',
    distance: 0.8,
    rating: 4.5,
    cleanlinessRating: 4.8,
    isOpen: true,
    isFree: true,
    hasWheelchairAccess: true,
    hasStrollerAccess: true,
    hasDiaperChange: true,
    hasFeedingArea: true,
    imageUrl: 'https://images.unsplash.com/photo-1595428774223-ef52624120d2?auto=format&fit=crop&q=80&w=400',
    location: { lat: 12.9958, lng: 77.6963 },
    floor: 'Level 2',
    locationDetails: 'East Wing, near Food Court',
    toiletStyle: 'Indian and Western',
    isRoadside: false,
    diversionDistance: 0.4,
    openTime: '10:00 AM',
    closeTime: '10:00 PM',
  },
  {
    id: '10',
    name: 'Shell Highway Oasis',
    type: 'Highway Service',
    address: 'Bangalore-Pune Highway, NH 48',
    distance: 5.2,
    rating: 4.6,
    cleanlinessRating: 4.7,
    isOpen: true,
    isFree: true,
    hasWheelchairAccess: true,
    hasStrollerAccess: true,
    hasDiaperChange: true,
    hasFeedingArea: true,
    imageUrl: 'https://images.unsplash.com/photo-1545127398-14699f92334b?auto=format&fit=crop&q=80&w=400',
    location: { lat: 13.0251, lng: 77.5340 },
    floor: 'Main Complex',
    locationDetails: 'Directly on Highway side',
    toiletStyle: 'Western',
    isRoadside: true,
    diversionDistance: 0,
    openTime: 'Open 24/7',
  },
  {
    id: '11',
    name: 'Public Pay & Use - MG Road',
    type: 'Public Pay & Use',
    address: 'Opposite Metro Station, MG Road',
    distance: 0.3,
    rating: 3.5,
    cleanlinessRating: 3.2,
    isOpen: true,
    isFree: false,
    hasWheelchairAccess: false,
    hasStrollerAccess: false,
    hasDiaperChange: false,
    hasFeedingArea: false,
    imageUrl: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&q=80&w=400',
    location: { lat: 12.9756, lng: 77.6067 },
    locationDetails: 'Street level roadside',
    toiletStyle: 'Indian',
    isRoadside: true,
    diversionDistance: 0,
    openTime: '05:00 AM',
    closeTime: '11:00 PM',
  },
  {
    id: '2',
    name: 'HP Petrol Bunk Service',
    type: 'Petrol Bunk',
    address: 'HAL Old Airport Rd, Bengaluru',
    distance: 1.2,
    rating: 3.8,
    cleanlinessRating: 3.5,
    isOpen: true,
    isFree: true,
    hasWheelchairAccess: false,
    hasStrollerAccess: false,
    hasDiaperChange: false,
    hasFeedingArea: false,
    imageUrl: 'https://images.unsplash.com/photo-1527018601619-a508a2be00cd?auto=format&fit=crop&q=80&w=400',
    location: { lat: 12.9591, lng: 77.6444 },
    toiletStyle: 'Indian',
    isRoadside: true,
    diversionDistance: 0,
    openTime: 'Open 24/7',
  }
];
